# Generated by Django 5.1.1 on 2024-09-30 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporturi', '0005_transport_is_allocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_pallets', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transport',
            name='selected_transporter',
        ),
        migrations.AddField(
            model_name='transport',
            name='full_vehicle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='number_of_pallets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporturi.vehicletype'),
        ),
    ]
