# Generated by Django 5.1.1 on 2024-10-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporturi', '0007_transport_allocated_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='nr_masina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
