# Generated by Django 5.1.1 on 2024-10-15 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporturi', '0010_transport_current_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='delivery_date',
            field=models.DateTimeField(verbose_name='Data de livrare'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Destinatie'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='is_allocated',
            field=models.BooleanField(default=False, verbose_name='Alocat'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Finalizat'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='is_departed',
            field=models.BooleanField(default=False, verbose_name='Plecat'),
        ),
        migrations.CreateModel(
            name='TransportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporturi.transport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='calcul_transporturi/transport_files/')),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='transporturi.transport')),
            ],
        ),
    ]
