# Generated by Django 5.1.1 on 2024-10-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Transportator', 'Transportator'), ('Client', 'Client'), ('Staff', 'Staff')], default='Client', max_length=15),
        ),
    ]
